services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: safi123 
      POSTGRES_DB: safi_shariff_db
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      FLASK_ENV: testing
      DATABASE_URL: postgres://postgres:safi123@db:5432/safi_shariff_db
      SECRET_KEY: cddae684c792dde2151cd4c4c7bd8a28324917339720075e
    ports:
      - "5001:5000"
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8082:80"
    depends_on:
      - backend

volumes:
  db_data:
